[
  "tests/test_auth.py::UserTestCase::test_can_login_user",
  "tests/test_auth.py::UserTestCase::test_can_signup_user",
  "tests/test_auth.py::UserTestCase::test_email_validity",
  "tests/test_auth.py::UserTestCase::test_last_name_is_not_a_string",
  "tests/test_auth.py::UserTestCase::test_missing_first_name",
  "tests/test_auth.py::UserTestCase::test_missing_last_name",
  "tests/test_auth.py::UserTestCase::test_password_strength",
  "tests/test_auth.py::UserTestCase::test_phone_number_is_invalid",
  "tests/test_auth.py::UserTestCase::test_register_with_missing_fields",
  "tests/test_auth.py::UserTestCase::test_returns_error_if_email_is_missing",
  "tests/test_auth.py::UserTestCase::test_returns_error_if_first_name_not_string",
  "tests/test_auth.py::UserTestCase::test_returns_error_if_phone_number_is_missing",
  "tests/test_auth.py::UserTestCase::test_returns_error_if_user_already_exists",
  "tests/test_auth.py::UserTestCase::test_returns_error_if_username_is_not_valid",
  "tests/test_auth.py::UserTestCase::test_returns_error_on_failure_to_login",
  "tests/test_auth.py::UserTestCase::test_user_name_missing",
  "tests/test_auth.py::UserTestCase::test_validity_of_password",
  "tests/test_create_intervention.py::CreateInterventionTestCase::test_create_intervention",
  "tests/test_create_intervention.py::CreateInterventionTestCase::test_create_intervention_missing_fields",
  "tests/test_create_redflag.py::CreateReadFlagTestCase::test_create_redflag",
  "tests/test_create_redflag.py::CreateReadFlagTestCase::test_create_redflag_missing_fields",
  "tests/test_get_intervention.py::GetInterventionTestCase::test_get_all_interventions",
  "tests/test_get_intervention.py::GetInterventionTestCase::test_get_one_intervention_record",
  "tests/test_get_intervention.py::GetInterventionTestCase::test_returns_error_if_intervention_record_not_found",
  "tests/test_get_redflag.py::GetRedFlagTestCase::test_get_all_redflag",
  "tests/test_get_redflag.py::GetRedFlagTestCase::test_get_one_redflag",
  "tests/test_get_redflag.py::GetRedFlagTestCase::test_returns_error_if_incident_record_not_found"
]